### ISSUE TITLE
Nested configuration parameters

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#151]
I'm wondering how easy it is to support nested parameters in configuration file, for example in my configuration:

```yaml
analysis:
  qnorm: 1
  cis: 5
```
and in my SoS I can do something like `${CONFIG.analysis["qnorm"]}`. Currently this is not possible.
